--llink/1234
--users
CREATE TABLE USERS
(
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    STUDENT_ID VARCHAR2(20),
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER',
    CREATED_AT DATE DEFAULT SYSDATE
);

--lost items
CREATE TABLE LOST_ITEMS
(
    LOST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50),
    COLOR VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    LOST_LOCATION VARCHAR2(200),
    LOST_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LOST_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

--found items
CREATE TABLE FOUND_ITEMS
(
    FOUND_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50),
    COLOR VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    FOUND_LOCATION VARCHAR2(200),
    FOUND_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'UNCLAIMED',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_FOUND_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);


--claims
CREATE TABLE CLAIMS
(
    CLAIM_ID NUMBER PRIMARY KEY,
    FOUND_ID NUMBER NOT NULL,
    CLAIMANT_ID NUMBER NOT NULL,
    PROOF_TEXT VARCHAR2(2000),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_CLAIM_FOUND FOREIGN KEY(FOUND_ID) REFERENCES FOUND_ITEMS(FOUND_ID),
    CONSTRAINT FK_CLAIM_USER FOREIGN KEY(CLAIMANT_ID) REFERENCES USERS(USER_ID)
);

--matches
CREATE TABLE MATCHES
(
    MATCH_ID NUMBER PRIMARY KEY,
    LOST_ID NUMBER NOT NULL,
    FOUND_ID NUMBER NOT NULL,
    MATCH_SCORE NUMBER(5,2),
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_MATCH_LOST FOREIGN KEY(LOST_ID) REFERENCES LOST_ITEMS(LOST_ID),
    CONSTRAINT FK_MATCH_FOUND FOREIGN KEY(FOUND_ID) REFERENCES FOUND_ITEMS(FOUND_ID)
);

--notifications
CREATE TABLE NOTIFICATIONS
(
    NOTIFICATION_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    MESSAGE VARCHAR2(500),
    IS_READ NUMBER(1) DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);


