--llink/1234
--users
CREATE TABLE USERS
(
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    STUDENT_ID VARCHAR2(20),
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER',
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USERS_BI
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT USERS_SEQ.NEXTVAL
        INTO :NEW.USER_ID
        FROM DUAL;
    END IF;
END;
/

--lost items
CREATE TABLE LOST_ITEMS
(
    LOST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50),
    COLOR VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    LOST_LOCATION VARCHAR2(200),
    LOST_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LOST_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE LOST_ITEMS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER LOST_ITEMS_BI
BEFORE INSERT ON LOST_ITEMS
FOR EACH ROW
BEGIN
    IF :NEW.LOST_ID IS NULL THEN
        SELECT LOST_ITEMS_SEQ.NEXTVAL
        INTO :NEW.LOST_ID
        FROM DUAL;
    END IF;
END;
/

--found items
CREATE TABLE FOUND_ITEMS
(
    FOUND_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(50),
    COLOR VARCHAR2(50),
    DESCRIPTION VARCHAR2(1000),
    FOUND_LOCATION VARCHAR2(200),
    FOUND_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'UNCLAIMED',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_FOUND_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE FOUND_ITEMS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER FOUND_ITEMS_BI
BEFORE INSERT ON FOUND_ITEMS
FOR EACH ROW
BEGIN
    IF :NEW.FOUND_ID IS NULL THEN
        SELECT FOUND_ITEMS_SEQ.NEXTVAL
        INTO :NEW.FOUND_ID
        FROM DUAL;
    END IF;
END;
/

--claims
CREATE TABLE CLAIMS
(
    CLAIM_ID NUMBER PRIMARY KEY,
    FOUND_ID NUMBER NOT NULL,
    CLAIMANT_ID NUMBER NOT NULL,
    PROOF_TEXT VARCHAR2(2000),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_CLAIM_FOUND FOREIGN KEY(FOUND_ID) REFERENCES FOUND_ITEMS(FOUND_ID),
    CONSTRAINT FK_CLAIM_USER FOREIGN KEY(CLAIMANT_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE CLAIMS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CLAIMS_BI
BEFORE INSERT ON CLAIMS
FOR EACH ROW
BEGIN
    IF :NEW.CLAIM_ID IS NULL THEN
        SELECT CLAIMS_SEQ.NEXTVAL
        INTO :NEW.CLAIM_ID
        FROM DUAL;
    END IF;
END;
/

--matches
CREATE TABLE MATCHES
(
    MATCH_ID NUMBER PRIMARY KEY,
    LOST_ID NUMBER NOT NULL,
    FOUND_ID NUMBER NOT NULL,
    MATCH_SCORE NUMBER(5,2),
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_MATCH_LOST FOREIGN KEY(LOST_ID) REFERENCES LOST_ITEMS(LOST_ID),
    CONSTRAINT FK_MATCH_FOUND FOREIGN KEY(FOUND_ID) REFERENCES FOUND_ITEMS(FOUND_ID)
);

CREATE SEQUENCE MATCHES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER MATCHES_BI
BEFORE INSERT ON MATCHES
FOR EACH ROW
BEGIN
    IF :NEW.MATCH_ID IS NULL THEN
        SELECT MATCHES_SEQ.NEXTVAL
        INTO :NEW.MATCH_ID
        FROM DUAL;
    END IF;
END;
/

--notifications
CREATE TABLE NOTIFICATIONS
(
    NOTIFICATION_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    MESSAGE VARCHAR2(500),
    IS_READ NUMBER(1) DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE NOTIFICATIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NOTIFICATIONS_BI
BEFORE INSERT ON NOTIFICATIONS
FOR EACH ROW
BEGIN
    IF :NEW.NOTIFICATION_ID IS NULL THEN
        SELECT NOTIFICATIONS_SEQ.NEXTVAL
        INTO :NEW.NOTIFICATION_ID
        FROM DUAL;
    END IF;
END;
/


--messages
CREATE TABLE MESSAGES
(
    MESSAGE_ID NUMBER PRIMARY KEY,
    MATCH_ID NUMBER NOT NULL,
    SENDER_ID NUMBER NOT NULL,
    MESSAGE_TEXT VARCHAR2(1000) NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_MSG_MATCH FOREIGN KEY(MATCH_ID) REFERENCES MATCHES(MATCH_ID),
    CONSTRAINT FK_MSG_SENDER FOREIGN KEY(SENDER_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE MESSAGES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER MESSAGES_BI
BEFORE INSERT ON MESSAGES
FOR EACH ROW
BEGIN
    IF :NEW.MESSAGE_ID IS NULL THEN
        SELECT MESSAGES_SEQ.NEXTVAL
        INTO :NEW.MESSAGE_ID
        FROM DUAL;
    END IF;
END;
/

--item images
CREATE TABLE ITEM_IMAGES
(
    IMAGE_ID NUMBER PRIMARY KEY,
    LOST_ID NUMBER,
    FOUND_ID NUMBER,
    IMAGE_PATH VARCHAR2(255) NOT NULL,
    UPLOADED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_IMG_LOST FOREIGN KEY(LOST_ID) REFERENCES LOST_ITEMS(LOST_ID),
    CONSTRAINT FK_IMG_FOUND FOREIGN KEY(FOUND_ID) REFERENCES FOUND_ITEMS(FOUND_ID)
);

CREATE SEQUENCE ITEM_IMAGES_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ITEM_IMAGES_BI
BEFORE INSERT ON ITEM_IMAGES
FOR EACH ROW
BEGIN
    IF :NEW.IMAGE_ID IS NULL THEN
        SELECT ITEM_IMAGES_SEQ.NEXTVAL
        INTO :NEW.IMAGE_ID
        FROM DUAL;
    END IF;
END;
/

